# Generated by Django 6.0.4 on 2026-04-25 14:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'merchant',
            },
        ),
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('key', models.UUIDField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='IN_PROGRESS', max_length=20)),
                ('response_status', models.IntegerField(blank=True, help_text='HTTP status code of the completed response.', null=True)),
                ('response_body', models.JSONField(blank=True, help_text='JSON-serialised response body for replay.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='idempotency_keys', to='ledger.merchant')),
            ],
            options={
                'db_table': 'idempotency_key',
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_paise', models.BigIntegerField(help_text='Payout amount in the smallest currency unit (paise).')),
                ('bank_account_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='ledger.merchant')),
            ],
            options={
                'db_table': 'payout',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_paise', models.BigIntegerField(help_text='Entry amount in the smallest currency unit (paise). Always positive.')),
                ('entry_type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='ledger.merchant')),
                ('reference_payout', models.ForeignKey(blank=True, help_text='The payout that triggered this ledger entry, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='ledger.payout')),
            ],
            options={
                'db_table': 'ledger_entry',
                'ordering': ['-created_at'],
            },
        ),
    ]
